# Generated by Django 4.2.11 on 2024-11-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(unique=True)),
                ('price', models.IntegerField()),
                ('image', models.URLField()),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('feedback', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
