# Generated by Django 4.2.11 on 2024-11-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(unique=True)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('open', 'Open'), ('completed', 'Completed')], max_length=20)),
                ('team_uuids', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('badge_uuid', models.UUIDField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('open', 'Open'), ('in progress', 'In progress'), ('review', 'Review'), ('completed', 'Completed')], max_length=20)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('assignee_id', models.UUIDField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('member_uuids', models.JSONField(blank=True, null=True)),
                ('task_uuids', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
