version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network
    restart: always

  web:
    build: ./snapgoaltask
    volumes:
      - ./snapgoaltask:/app
    ports:
      - "3000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=snapgoaltask.settings
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - django_network
    command:
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always


volumes:
  postgres_data:

networks:
  django_network:
