openapi: 3.0.0
info:
  title: Badge API
  description: API for managing badges
  version: 1.0.0
paths:
  /badge:
    get:
      summary: List all badges
      operationId: listBadges
      responses:
        '200':
          description: A list of badges
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Badge'

    post:
      summary: Create a new badge
      operationId: createBadge
      requestBody:
        description: Badge object to be created
        content:
          application/json:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The file to be uploaded (image)
        required:
          - file
      responses:
        '201':
          description: Badge created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: uuid
                    example: '550e8400-e29b-41d4-a716-446655440000'
          
  /badge/{uuid}:
    post:
      summary: Create a new badge
      operationId: createBadgeAttr
      requestBody:
        description: Badge object to be created
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/Badge'
        required:
          - file
      responses:
        '201':
          description: Badge created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Badge'
    get:
      summary: Get a specific badge by ID
      operationId: getBadgeById
      parameters:
        - name: uuid
          in: path
          description: UUID of the badge to fetch
          required: true
          schema:
            type: uuid
      responses:
        '200':
          description: Badge details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Badge'
        '404':
          description: Badge not found

components:
  schemas:
    Badge:
      type: object
      properties:
        uuid:
          type: uuid
          example: '550e8400-e29b-41d4-a716-446655440000'
        title:
          type: string
          example: 'High Priority'
        description:
          type: string
          example: 'Awarded for high priority tasks.'
        points:
          type: integer
          example: 10
        image_url:
          type: string
          format: uri
          example: 'https://example.com/images/high_priority.png'
      required:
        - title
        - points
        - image_url
